# Install script for directory: /home/user/linuxcnc/cmake

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Debug")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/rtapi/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/linuxcnc_module_helper/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/liblinuxcnchal/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/liblinuxcncini/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/libtooldata/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/libnml/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/liblinuxcnc/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/libposemath/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/libpyplugin/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/librs274/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/libcanterp/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/hal_lib/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/test/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/tp/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/tpmod/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/homemod/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/threads/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/ethercat/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/lineardeltakins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/rotarydeltakins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/pumakins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/genserkins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/5axiskins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/trivkins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/rotatekins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/xyzac-trt-kins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/xyzbc-trt-kins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/switchkins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/pentakins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/scorbotkins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/tripodkins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/scarakins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/maxkins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/corexykins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/genhexkins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/rosekins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/ugenserkins/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/scurve/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/motmod/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/inivar/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/halcmd/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/halmeter/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/halscope/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/classicladder/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/halui/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/halrmt/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/pci_write/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/pci_read/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/motion_logger/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/sai/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/linuxcncsvr/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/milltask/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/linuxcncrsh/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/schedrmt/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/linuxcnclcd/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/linuxcnc_tlc/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/hal_tlc/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/lineardeltakins_py/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/rotarydeltakins_py/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/hal_py/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/togl_py/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/linuxcnc_py/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/gcode_py/cmake_install.cmake")
  include("/home/user/linuxcnc/build-cmake-Desktop-Debug/components/sc_tp/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/home/user/linuxcnc/build-cmake-Desktop-Debug/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
