#!/bin/sh
echo "current folder:"
echo $PWD
echo "\n"

echo "check dependencies. \n"
sudo apt-get install libeigen3-dev

#echo "copy python scripts to ~/bin folder. \n"
#cd ..
#cd scripts
#cp -rf * ../bin
#cd ..

echo "run check and set scripts. \n"
cd ..
cd src
./autogen.sh
./configure --enable-non-distributable=yes --with-realtime=uspace
cd ..

echo "Copying header files into the include directory to use with halcompile \n"
cd src/rtapi
cp *.h ../../include
cd ..
cd hal
cp *.h ../../include
cd ..
cd ..


echo "Building & installing components needed by the axis gui. \nBuilding with halcompile. \n"
cd scripts
./rip-environment halcompile --install ../src/hal/components/ddt.comp
./rip-environment halcompile --install ../src/hal/components/hypot.comp
./rip-environment halcompile --install ../src/hal/components/sim_spindle.comp
./rip-environment halcompile --install ../src/hal/components/limit2.comp
./rip-environment halcompile --install ../src/hal/components/lowpass.comp
./rip-environment halcompile --install ../src/hal/components/near.comp
./rip-environment halcompile --install ../src/hal/components/scale.comp
./rip-environment halcompile --install ../src/hal/components/or2.comp
./rip-environment halcompile --install ../src/hal/components/comp.comp
./rip-environment halcompile --install ../src/hal/components/and2.comp
./rip-environment halcompile --install ../src/hal/components/wcomp.comp
./rip-environment halcompile --install ../src/hal/components/match8.comp
./rip-environment halcompile --install ../src/hal/components/mux2.comp
./rip-environment halcompile --install ../src/hal/components/mux4.comp
./rip-environment halcompile --install ../src/hal/components/mux8.comp
./rip-environment halcompile --install ../src/hal/components/mux16.comp
./rip-environment halcompile --install ../src/hal/components/sim_home_switch.comp
cd ..

echo "Building linuxcnc with cmake. \n"
cd cmake
mkdir -p build
cd build
cmake -DBUILD_USPACE=ON ..
make
make install
cd ..
cd ..

echo "current folder:"
echo $PWD
echo "\n"

# Recreate the Sudo Make Setuid command (needed for running real machines)
# This version is from : https://github.com/grotius-cnc/hal-core/blob/main/make
echo "Running equivalent of Sudo Make Setuid. \n"
sudo chown 777 -R bin/rtapi_app
sudo chown 777 -R bin/linuxcnc_module_helper
sudo chmod 777 bin/rtapi_app
sudo chmod 777 bin/linuxcnc_module_helper

echo "Start linuxcnc. \n"
cd scripts
./rip-environment linuxcnc ../configs/sim/axis/axis_mm.ini

# Example to start with custom trajectory planner or use in ini file : [TRAJ]TPMOD=user_tpcomp
# ./rip-environment linuxcnc -t tpmod_scurve ../configs/sim/axis/axis_mm.ini

