#!/bin/sh
echo "current folder:"
echo $PWD
echo "\n"

echo "clean current linuxcnc installation."
./clean_all

echo "copy python scripts to ~/bin folder"
cd ..
cd scripts
cp -rf * ../bin
cd ..

echo "run check and set scripts. \n"
cd src
./autogen.sh
./configure --enable-non-distributable=yes --with-realtime=uspace
cd ..

echo "Copying header files into the include directory to use with halcompile \n"
cd src/rtapi
cp *.h ../../include
cd ..
cd hal
cp *.h ../../include
cd ..
cd ..


echo "building & installing components needed by the axis gui. \nBuilding with halcompile. \n"
cd scripts
./rip-environment halcompile --install ../src/hal/components/ddt.comp
./rip-environment halcompile --install ../src/hal/components/hypot.comp
./rip-environment halcompile --install ../src/hal/components/sim_spindle.comp
./rip-environment halcompile --install ../src/hal/components/limit2.comp
./rip-environment halcompile --install ../src/hal/components/lowpass.comp
./rip-environment halcompile --install ../src/hal/components/near.comp
./rip-environment halcompile --install ../src/hal/components/scale.comp
./rip-environment halcompile --install ../src/hal/components/or2.comp
./rip-environment halcompile --install ../src/hal/components/comp.comp
./rip-environment halcompile --install ../src/hal/components/and2.comp
cd ..

echo "building linuxcnc with cmake. \n"
cd cmake
mkdir -p build
cd build
cmake -DBUILD_USPACE=ON ..
make
make install
cd ..
cd ..

# Recreate the Sudo Make Setuid command (needed for running real machines)
#echo "Running equivalent of Sudo Make Setuid"
#sudo chown root bin/rtapi_app
#sudo chmod 4750 bin/rtapi_app
#sudo chown root bin/linuxcnc_module_helper.so
#sudo chmod 4750 bin/linuxcnc_module_helper.so

echo "start linuxcnc \n"
cd scripts
./rip-environment linuxcnc ../configs/sim/axis/axis_mm.ini

# Example to start with custom trajectory planner or use in ini file : [TRAJ]TPMOD=user_tpcomp
# ./rip-environment linuxcnc -t tpmod_scurve ../configs/sim/axis/axis_mm.ini

