#!/bin/sh

# This script clean's up linuxcnc. This script clean's linuxcnc for a github push.

echo "current folder:"
echo $PWD
echo "\n"

echo "clean qt-cmake config file \n"
rm -rf CMakeLists.txt.user

cd ..

echo "Uncomment these following two if you are running on real hardware and ran the setuid-alike command in build"
#sudo rm bin/rtapi_app
#sudo rm bin/linuxcnc_module_helper.so

echo "clean ~/bin folder \n"
cd bin
rm -rf *
cd ..

echo "clean ~/rtlib folder \n"
cd rtlib
rm -rf *
cd ..

echo "clean ~/include folder \n"
cd include
rm -rf *
cd ..

echo "clean library's \n"
cd lib
rm -rf *.so
rm -rf *.so.0
rm -rf *.a
cd python
rm -rf *.so
rm -rf *.so.0
rm -rf *.a
cd .. 
cd .. 

