#!/bin/sh

# This script clean's up linuxcnc.

echo "Current folder:"
echo $PWD
echo "\n"

echo "Remove qt-cmake config file. \n"
rm -rf CMakeLists.txt.user

cd ..

echo "Uncomment these following two if you are running on real hardware and ran the setuid-alike command in build. "
sudo rm bin/rtapi_app
sudo rm bin/linuxcnc_module_helper.so

echo "Clean ~/bin folder. \n"
cd bin
rm -rf *
cd ..

echo "Clean ~/rtlib folder. \n"
cd rtlib
rm -rf *
cd ..

echo "Clean ~/include folder. \n"
cd include
rm -rf *
cd ..

echo "Clean library's. \n"
cd lib
rm -rf *.so
rm -rf *.so.0
rm -rf *.a
cd python
rm -rf *.so
rm -rf *.so.0
rm -rf *.a
cd .. 
cd .. 

